### ISSUE TITLE
How to confirm the accuracy of Cnic Codes

### ISSUE THREAD

**Issue by 791135976** [graysuit/cnic#5]
Will Cnic Codes be updated every years?

**Comment by 791135976** [comment]
i mean first 5 codes,

**Comment by 791135976** [comment]
www.pbs.gov.pk show Abbottabad is 101,but 131 in the list.

**Comment by graysuit** [comment]
> Will Cnic Codes be updated every years?

Codes remain same. They change only when creating new district/municipality which rarely happened in last 30 years.



> [www.pbs.gov.pk](http://www.pbs.gov.pk) show Abbottabad is 101,but 131 in the list.

101,131 etc are not valid cnic codes. Its for different purpose i guess, i don't know

Take anyone's cnic and tell me if it give any wrong information.

**Comment by 791135976** [comment]
I will confirm it, thanks. Any questions, where can i find the codes in web?

**Comment by 791135976** [comment]
I find 42201 is KARACHI-east,and 42202,42203,42204 means KARACHI-WEST, KARACHI-MID, KARACHI-NORTH. It is have something update?

**Comment by graysuit** [comment]
> I will confirm it, thanks. Any questions, where can i find the codes in web?

https://github.com/graysuit/cnic/blob/main/cnic_codes_list.md

> I find 42201 is KARACHI-east,and 42202,42203,42204 means KARACHI-WEST, KARACHI-MID, KARACHI-NORTH. It is have something update?

check: https://graysuit.github.io/cnic
